sudo: false

language: node_js

node_js:
  - "0.10.45"

cache:
    directories:
    - $HOME/.meteor
    - $HOME/.npm

notifications:
  slack:
    secure: Sp0XScJQvQJmAD842c3+NRfcz/kmY3t01vyqcqywGBp+AtpYrTCT8ZXWzxSsS5+0Zyxbw5qHo+cApjvaP3pWKRYYoCz8OQ41cJ5m7CauvRXhLNlGph9fzSk5f1s6Ut1efXlFRY/DQhFPuHw8OdsrahIrgoLSYoJvPU3oc2aBszo=

before_install:
  - export PATH="$HOME/.meteor:$PATH"
  - export REPO_HOME="$TRAVIS_BUILD_DIR"
  - export PACKAGE_DIRS="$TRAVIS_BUILD_DIR/../"
  - "meteor/bin/install-meteor.sh"
  - "npm install -g spacejam"
