sudo: false

language: node_js

node_js:
  - "0.10.36"

before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - "npm install -g spacejam"
  - export PATH="$HOME/.meteor:$PATH"
  - "meteor --release 1.3-rc.1 --help"

script: "spacejam --release 1.3-rc.1 test-packages ./"
